name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"  # daily at 02:00 UTC

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest -q

  nightly-ingestion:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run ingestion for 120 users per system
        env:
          FETCH_COUNT: "120"
        run: python src/main.py
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/*.csv
          if-no-files-found: ignore